import { promises as fs } from 'node:fs';
import path from 'node:path';

type TokenGroup = {
  groupName: string; // e.g. "colors"
  typeName: string; // e.g. "ColorToken"
  tokens: Record<string, string>;
};

const TOKENS_DIR = path.resolve(process.cwd(), 'src/styles/tokens');
const OUT_DIR = path.resolve(process.cwd(), 'src/styles/generated');

const CSS_OUT = path.join(OUT_DIR, 'tokens.css');
const DTS_OUT = path.join(OUT_DIR, 'tokens.d.ts');

const TYPE_NAME_BY_FILE: Record<string, string> = {
  'colors.json': 'ColorToken',
  'spacing.json': 'SpacingToken',
  'radius.json': 'RadiusToken',
  'typography.json': 'TypographyToken',
  'sizes.json': 'SizeToken',
  'borders.json': 'BorderToken',
  'layout.json': 'LayoutToken',
  'motion.json': 'MotionToken',
  'shadow.json': 'ShadowToken',
  'scrollbar.json': 'ScrollbarToken',
  'z-index.json': 'ZIndexToken',
};

function toKebab(s: string) {
  return s.replace(/[^a-zA-Z0-9_-]/g, '-');
}

function sortKeys(obj: Record<string, string>) {
  return Object.keys(obj)
    .sort((a, b) => a.localeCompare(b, 'en'))
    .reduce(
      (acc, k) => {
        acc[k] = obj[k];
        return acc;
      },
      {} as Record<string, string>
    );
}

function unionType(typeName: string, keys: string[]) {
  if (!keys.length) return `export type ${typeName} = never;\n`;

  const lines = keys.map((k) => `  | '${k}'`).join('\n');
  return `export type ${typeName} =\n${lines};\n`;
}

async function readJson(filePath: string) {
  const raw = await fs.readFile(filePath, 'utf8');
  const parsed = JSON.parse(raw) as Record<string, string>;
  // normalize: stringify all values
  const normalized: Record<string, string> = {};
  for (const [k, v] of Object.entries(parsed)) {
    normalized[toKebab(k)] = String(v);
  }
  return normalized;
}

async function main() {
  await fs.mkdir(OUT_DIR, { recursive: true });

  const files = (await fs.readdir(TOKENS_DIR))
    .filter((f) => f.endsWith('.json'))
    .sort((a, b) => a.localeCompare(b, 'en'));

  const groups: TokenGroup[] = [];

  for (const file of files) {
    const filePath = path.join(TOKENS_DIR, file);
    const tokens = sortKeys(await readJson(filePath));

    const typeName = TYPE_NAME_BY_FILE[file] ?? `${pascalCase(file.replace('.json', ''))}Token`;
    groups.push({
      groupName: file.replace('.json', ''),
      typeName,
      tokens,
    });
  }

  // ---- CSS generation
  const cssParts: string[] = [];
  cssParts.push('/* AUTO-GENERATED FILE. DO NOT EDIT. */');
  cssParts.push('/* Generated by scripts/generate-tokens.ts */');
  cssParts.push('');
  cssParts.push(':root {');

  for (const g of groups) {
    cssParts.push(`  /* ${g.groupName} */`);
    for (const [name, value] of Object.entries(g.tokens)) {
      cssParts.push(`  --${name}: ${value};`);
    }
    cssParts.push('');
  }

  // remove trailing empty line if exists
  if (cssParts[cssParts.length - 1] === '') cssParts.pop();
  cssParts.push('}');
  cssParts.push('');

  await fs.writeFile(CSS_OUT, cssParts.join('\n'), 'utf8');

  // ---- DTS generation
  const dtsParts: string[] = [];
  dtsParts.push('/* AUTO-GENERATED FILE. DO NOT EDIT. */');
  dtsParts.push('/* Generated by scripts/generate-tokens.ts */');
  dtsParts.push('');

  for (const g of groups) {
    const keys = Object.keys(g.tokens);
    dtsParts.push(unionType(g.typeName, keys));
    dtsParts.push('');
  }

  // Combined helper union
  const allTypeNames = groups.map((g) => g.typeName).sort((a, b) => a.localeCompare(b, 'en'));
  dtsParts.push(`export type TokenName = ${allTypeNames.join(' | ')};`);
  dtsParts.push('');

  await fs.writeFile(DTS_OUT, dtsParts.join('\n'), 'utf8');

  // eslint-disable-next-line no-console
  console.log(`[tokens] generated:\n- ${CSS_OUT}\n- ${DTS_OUT}`);
}

function pascalCase(input: string) {
  return input
    .split(/[-_.]/g)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
}

main().catch((e) => {
  // eslint-disable-next-line no-console
  console.error(e);
  process.exit(1);
});
